clear all;
clc;
% Define images to process
imageFileNames = {'.\Figure_Test_BeforeCalibration\1.jpg',...
    '.\Figure_Test_BeforeCalibration\2.jpg',...
    '.\Figure_Test_BeforeCalibration\3.jpg',...
    '.\Figure_Test_BeforeCalibration\4.jpg',...
    '.\Figure_Test_BeforeCalibration\5.jpg',...
    '.\Figure_Test_BeforeCalibration\6.jpg',...
    '.\Figure_Test_BeforeCalibration\7.jpg',...
    '.\Figure_Test_BeforeCalibration\9.jpg',...
    '.\Figure_Test_BeforeCalibration\10.jpg',...
    '.\Figure_Test_BeforeCalibration\11.jpg',...
    '.\Figure_Test_BeforeCalibration\12.jpg',...
    '.\Figure_Test_BeforeCalibration\13.jpg',...
    '.\Figure_Test_BeforeCalibration\14.jpg',...
    '.\Figure_Test_BeforeCalibration\15.jpg',...
    '.\Figure_Test_BeforeCalibration\16.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage=imread(imageFileNames{1});
[mrows,ncols,~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize=1.750000e+01;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure;showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure;showExtrinsics(cameraParams,'CameraCentric');
h3=figure;showExtrinsics(cameraParams,'PatternCentric');

IntrinsicMatrix=cameraParams.IntrinsicMatrix
RadialDistortion=cameraParams.RadialDistortion
TangentialDistortion=cameraParams.TangentialDistortion
% undistortedImage=undistortImage(originalImage,cameraParams);

